/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Komal
 */
import javax.swing.*;
import java.awt.*;
import java.sql.*;
public class AdminLogin extends javax.swing.JFrame {

    /**
     * Creates new form AdminLogin
     */
    int ad=0;
    String id;
    public AdminLogin() {
        initComponents();
        Sign_In5.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Username_Label = new javax.swing.JLabel();
        Sign_In = new javax.swing.JPanel();
        Username_Label2 = new javax.swing.JLabel();
        Password_Label1 = new javax.swing.JLabel();
        Username_Input1 = new javax.swing.JTextField();
        Password_Input1 = new javax.swing.JTextField();
        Sign_Up_Btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Home_Label = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        Sign_In5 = new javax.swing.JPanel();
        Username_Label6 = new javax.swing.JLabel();
        Password_Label5 = new javax.swing.JLabel();
        Login_Id = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        Password_Input5 = new javax.swing.JPasswordField();
        Home_Label1 = new javax.swing.JLabel();
        Back_Btn1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        Hospital_Radio = new javax.swing.JRadioButton();
        Vaccine_Radio = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();

        Username_Label.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Username_Label.setText("Username");

        Sign_In.setForeground(new java.awt.Color(102, 102, 255));

        Username_Label2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Username_Label2.setText("Username");

        Password_Label1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Password_Label1.setText("Password");

        Username_Input1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Username_Input1ActionPerformed(evt);
            }
        });

        Password_Input1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Password_Input1ActionPerformed(evt);
            }
        });

        Sign_Up_Btn.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        Sign_Up_Btn.setText("SignUp");
        Sign_Up_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sign_Up_BtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel1.setText("Not a user..?");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Set Your:");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButton1.setText("Enter");

        javax.swing.GroupLayout Sign_InLayout = new javax.swing.GroupLayout(Sign_In);
        Sign_In.setLayout(Sign_InLayout);
        Sign_InLayout.setHorizontalGroup(
            Sign_InLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Sign_InLayout.createSequentialGroup()
                .addGroup(Sign_InLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Sign_InLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Sign_InLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Username_Label2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(Password_Label1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Sign_InLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Password_Input1, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                            .addComponent(Username_Input1)))
                    .addGroup(Sign_InLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Sign_Up_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Sign_InLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        Sign_InLayout.setVerticalGroup(
            Sign_InLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Sign_InLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Sign_InLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Username_Label2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Username_Input1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Sign_InLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Password_Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Password_Input1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Sign_InLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sign_Up_Btn)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        Home_Label.setBackground(new java.awt.Color(0, 255, 255));
        Home_Label.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Home_Label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Home_Label.setText(" User Login");
        Home_Label.setToolTipText("");
        Home_Label.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        Home_Label.setAutoscrolls(true);
        Home_Label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Home_Label.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(585, 302));

        jPanel1.setBackground(new java.awt.Color(0, 204, 153));

        Sign_In5.setBackground(new java.awt.Color(204, 255, 204));
        Sign_In5.setForeground(new java.awt.Color(255, 255, 255));

        Username_Label6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Username_Label6.setText("Reg.no/CentreID:");

        Password_Label5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Password_Label5.setText("Password:");

        Login_Id.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Login_Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login_IdActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButton6.setText("Enter");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        Password_Input5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Password_Input5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Password_Input5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Sign_In5Layout = new javax.swing.GroupLayout(Sign_In5);
        Sign_In5.setLayout(Sign_In5Layout);
        Sign_In5Layout.setHorizontalGroup(
            Sign_In5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Sign_In5Layout.createSequentialGroup()
                .addGroup(Sign_In5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Sign_In5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Sign_In5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Username_Label6, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                            .addComponent(Password_Label5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(Sign_In5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Login_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Password_Input5, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Sign_In5Layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        Sign_In5Layout.setVerticalGroup(
            Sign_In5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Sign_In5Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(Sign_In5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Username_Label6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Login_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Sign_In5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Password_Label5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Password_Input5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(22, 22, 22))
        );

        Home_Label1.setBackground(new java.awt.Color(0, 255, 255));
        Home_Label1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Home_Label1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Home_Label1.setText("  Admin Login");
        Home_Label1.setToolTipText("");
        Home_Label1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        Home_Label1.setAutoscrolls(true);
        Home_Label1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Home_Label1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        Back_Btn1.setBackground(new java.awt.Color(255, 255, 255));
        Back_Btn1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Back_Btn1.setText("Back");
        Back_Btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_Btn1ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 204, 153));

        Hospital_Radio.setBackground(new java.awt.Color(0, 204, 153));
        Hospital_Radio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Hospital_Radio.setText("Hospital");
        Hospital_Radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Hospital_RadioActionPerformed(evt);
            }
        });

        Vaccine_Radio.setBackground(new java.awt.Color(0, 204, 153));
        Vaccine_Radio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Vaccine_Radio.setText("Vaccine Centre");
        Vaccine_Radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Vaccine_RadioActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("Select:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Hospital_Radio, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(Vaccine_Radio, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(162, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Hospital_Radio)
                    .addComponent(Vaccine_Radio)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Home_Label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(607, 607, 607))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Back_Btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(Sign_In5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Home_Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(Sign_In5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(Back_Btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Username_Input1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Username_Input1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Username_Input1ActionPerformed

    private void Password_Input1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Password_Input1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Password_Input1ActionPerformed

    private void Sign_Up_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sign_Up_BtnActionPerformed
        // TODO add your handling code here:
        Sign_Up_Btn.setVisible(false);
        jLabel1.setVisible(false);
        jLabel2.setVisible(true);
    }//GEN-LAST:event_Sign_Up_BtnActionPerformed

    private void Login_IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_IdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Login_IdActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        PreparedStatement ps;
        ResultSet rs;
        String sql="";
        if(Hospital_Radio.isSelected()==true)
        {
             sql="select * from admin where reg_no=? and password=?";
             ad=1;
        }
        else if(Vaccine_Radio.isSelected()==true){
             sql="select * from admin where centre_id=? and password=?";
             ad=2;
    }
        try{
            Connection con=CovidManagement.connector();
            ps=con.prepareStatement(sql);   
            ps.setString(1,Login_Id.getText());
            ps.setString(2,Password_Input5.getText());
            rs=ps.executeQuery();
            if(rs.next())
            {
                JOptionPane.showMessageDialog(null,"Correct Credentials!");
                id=Login_Id.getText();
                dispose();
                Admin_Duty a=new Admin_Duty(ad,id);
                if(ad==1)a.setVisible(true);
            }
            else 
            {
                JOptionPane.showMessageDialog(null,"Incorrect Credentials!Please try again!");
                Login_Id.setText("");
                Password_Input5.setText("");
            }
        }catch(SQLException e){}
    }//GEN-LAST:event_jButton6ActionPerformed

    private void Back_Btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_Btn1ActionPerformed
        // TODO add your handling code here:
        Home h=new Home();
        h.setVisible(true);
        dispose();
    }//GEN-LAST:event_Back_Btn1ActionPerformed

    private void Password_Input5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Password_Input5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Password_Input5ActionPerformed

    private void Hospital_RadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Hospital_RadioActionPerformed
        // TODO add your handling code here:
        Sign_In5.setVisible(true);
        Vaccine_Radio.setSelected(false);
        
    }//GEN-LAST:event_Hospital_RadioActionPerformed

    private void Vaccine_RadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Vaccine_RadioActionPerformed
        // TODO add your handling code here:
        Sign_In5.setVisible(true);
        Hospital_Radio.setSelected(false);
    }//GEN-LAST:event_Vaccine_RadioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_Btn1;
    private javax.swing.JLabel Home_Label;
    private javax.swing.JLabel Home_Label1;
    private javax.swing.JRadioButton Hospital_Radio;
    private javax.swing.JTextField Login_Id;
    private javax.swing.JTextField Password_Input1;
    private javax.swing.JPasswordField Password_Input5;
    private javax.swing.JLabel Password_Label1;
    private javax.swing.JLabel Password_Label5;
    private javax.swing.JPanel Sign_In;
    private javax.swing.JPanel Sign_In5;
    private javax.swing.JButton Sign_Up_Btn;
    private javax.swing.JTextField Username_Input1;
    private javax.swing.JLabel Username_Label;
    private javax.swing.JLabel Username_Label2;
    private javax.swing.JLabel Username_Label6;
    private javax.swing.JRadioButton Vaccine_Radio;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
